# Generated by Django 2.2 on 2019-04-04 15:36

from django.db import migrations
from django.conf import settings


def forward(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    site, created = Site.objects.using(db_alias).get_or_create(pk=settings.SITE_ID)
    site.name = settings.DOMAIN
    site.domain = settings.DOMAIN
    site.save()


def reverse(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    site = Site.objects.using(db_alias).get(pk=settings.SITE_ID)
    site.name = 'example.com'
    site.domain = 'example.com'
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]

